### ISSUE TITLE
Error when running python

### ISSUE THREAD

**Issue by peethanisairam** [QualityInformationFramework/qif-community#3]

**Comment by bobstoneorigin** [comment]
In QIF 1.0 there were two independent document types: QIFPlan and QIFResults which shared a common library. Since QIF 2.0 there is only one document type: QIFDocument. So even if your application is just QIF Plan related you need to build the whole QIFDocument bindings, and then just implement the QIF Plan portion in your application. So you must run pyxbgen with--schema-location=**QIFDocument.xsd**.

**Comment by peethanisairam** [comment]
thank you sir issue resolved.
