### ISSUE TITLE
[Question] Purpose of redefining CAD geometry/drawings in QIF MBD vs linking to existing model

### ISSUE THREAD

**Issue by Mark-A-White** [QualityInformationFramework/qif-community#5]
Hello Everyone,

I'm just getting my feet wet with QIF and AP242 trying to define where they have come from and are heading along with what a good implementation picture looks like. Have an initial question for the QIF folks here that will hopefully help the other pieces in this puzzle drop into place.

In reading up on QIF vs AP242 it looks like they were somewhat competing back around 2015 and that there are ongoing efforts to get the systems harmonized. The piece that confuses me the most is that QIF MBD (Section 7.0) seems to reproduce what is already defined in the design CAD model.  Per section 7.2 the goal is, "…an open, 3D model-based product definition (MBD). The model is independent of any CAD system." To me this appears to be an additional source of conversion error. Since depending on my supplier I may already be converting to another format (AP242 for instance if I want a non-proprietary format) why would I not simply link feature ID's directly to elements of the AP242 model? What benefit is seen by my risking a CAD conversion error both for transmitting solid geometry for CAM but then also in creating a second seperate model for quality purposes? I think this question extends over to QIF's support for fully laying out a drawing as well since again it creates error and in a format that fewer tools can readily open and view when the annotated model is already available.

Really appreciate your help as I try to get a more solid grasp of applying QIF!

Thank you,

Mark

**Comment by daniel-campbell** [comment]
Hi Mark, and welcome to the QIF Community!

You are correct that QIF MBD is a way to carry model geometry and PMI. For example, here is a NIST test model, entirely in QIF format:

![part](https://user-images.githubusercontent.com/10170984/72176772-b73b6e80-33a4-11ea-9bdb-94a2991c3408.png)

QIF is unique in that it is designed with gathering metrology-related data, and tying it to the model via its framework of data structures. It introduced a Persistent UUID capability for doing this.  It emphasizes shape features for metrology and has a very robust definition of product characteristics (e.g., dimensional & geometric tolerances, thread specification, welding specs for both GD&T and ISO GPS)  And it is a standard defined as an XML schema for easier validation, development, and extensibility.

Let me try to address some of your questions one by one. 

> To me this appears to be an additional source of conversion error.

If the original native CAD model is available and can be used, this would be the best way to go, generally speaking. It involves no conversions. But often, downstream software requires data in a standard format like QIF or STEP AP242. There exists validation software to validate the quality of CAD translations. 

> Since depending on my supplier I may already be converting to another format (AP242 for instance if I want a non-proprietary format) why would I not simply link feature ID's directly to elements of the AP242 model?

This is possible. QIF features and characteristics can link to external entity IDs, which can be IDs found in a STEP AP242, for example.  

> What benefit is seen by my risking a CAD conversion error both for transmitting solid geometry for CAM but then also in creating a second seperate model for quality purposes?

Most software which supports QIF will not support the complexity of mixed data sets (i.e., CAD/PMI in STEP242, measurement data in QIF). So this is why many are choosing to using QIF MBD. By the way, many users also generate IGES or STEP AP203/214 data as well, since legacy systems are sure to support that. 

> I think this question extends over to QIF's support for fully laying out a drawing as well since again it creates error and in a format that fewer tools can readily open and view when the annotated model is already available.

I’m not sure that I understand what you mean here, can you elaborate? 

I hope that these answers are at least a helpful start! Let us know what other questions you have. Or, if you would like to have a chat with some members of the DMSC about QIF, let me know and we can probably arrange a short call to discuss the details of QIF. 

Daniel

_PS: Thanks to @BrownCurtisW for providing some additional thoughts on this matter_

**Comment by Mark-A-White** [comment]
Hi Daniel,

Thank you (and @BrownCurtisW) for the detailed response to my question! I’ll have to dive more in depth as to the PMI support in QIF vs AP242 with regards to welding specifications etc. I had not yet had a chance to dive into the two standards to that level of detail yet. My focus so far had been at the GD&T / GDP level. At least at a high level first pass it doesn’t appear that there is a major gap in terms of supported PMI between the two standards.

One additional question your comment raised, 

> “Most software which supports QIF will not support the complexity of mixed data sets… So this is why many are choosing to using QIF MBD.” 

Have you seen any software packages outside of the metrology community trying to leverage QIF MBD? (IE CAM packages) I’m just curious how the format is being considered for use/abuse out in the real world beyond what I’ve been able to find so far.


With regards to my last question about the drawing layout, a couple additional reads through sections 7.5.7.5.18 and others were able to resolve the issues. Sometimes it takes me a few tries before I can get my head around things.


Thank you again,



Mark

**Comment by daniel-campbell** [comment]
> I’ll have to dive more in depth as to the PMI support in QIF vs AP242 with regards to welding specifications etc. I had not yet had a chance to dive into the two standards to that level of detail yet. My focus so far had been at the GD&T / GDP level. At least at a high level first pass it doesn’t appear that there is a major gap in terms of supported PMI between the two standards.

In general, QIF MBD and STEP 242 are very similar. It typically boils down to the question of: what software are you using, and which format(s) does it support?

Regarding welds, one thing that may be an issue right now is that (if I'm not mistaken) STEP242 does not support assembly level PMI, and it is not uncommon for weld symbols to be placed on assemblies. 

> Have you seen any software packages outside of the metrology community trying to leverage QIF MBD?

I have mostly seen it in the metrology area, but then again, there isn't as much uptake of MBD in general in CAM software. Maybe a little bit, but the benefit of reading the annotations is not as huge as for metrology. With CAM, only a few annotations are really important, but with metrology, basically every symbol of every callout is crucial. 

I have seen some non-dimensional quality software use QIF, and lots of tolerance stackup analysis software is at the very least taking a good hard look at it (and maybe more?).

Please let us know if you have any more questions! If you would like to discuss more, maybe we can set up a short call with some DMSC-ers.
